### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by kinow** [pmkruyen/dearscholar#28]
Hi @pmkruyen 

A few suggestions for the new documentation. I really liked the Wiki format. Having separate pages makes it easier to follow, and also shortens the documents. And thanks for mentioning me there :+1: but all I'm doing is just bothering you with issues until I can get it running :smile: you are the one doing the hard work here.

I will add notes here to what I think could be changed in the docs, as I don't have access to edit or suggest changes there (although I think it's possible to send PR's to Wiki? I think GitHub stores Wiki as some special ref in the git tree, anyhow).

## Docker container name

The command to start the container is `docker run -i -t -p "80:80" -v ${PWD}/app:/app -v ${PWD}/mysql:/var/lib/mysql mattrayner/lamp:latest-1804`, which creates a random name like  `dazzling_shirley` (actual name of my last container for DearScholar) or so. Then the other commands, like for setting up the database, cannot refer to the random name.

Instead, these commands use `docker exec -it CONTAINER_ID bash -l`, with `CONTAINER_ID` to define the container.

Instead, if the command used to start the container had the name definition, we could use it in the rest of the docs. e.g.

```bash
docker run --name dearscholar -i -t -p "80:80" -v ${PWD}/app:/app -v ${PWD}/mysql:/var/lib/mysql mattrayner/lamp:latest-1804
```

With **`--name dearscholar`**, we can now easily use the `dearscholar` name in other commands.

```bash
docker exec -it dearscholar bash -l
root@876aa5ef23be:/# 

```

## Automated installation

I will raise a PR with something I put together while building using your latest instructions @pmkruyen . It should allow users to run the server backend with a couple commands. Feel free to close the PR and re-use it if you prefer to change things, or merge and modify, etc.

Just thought it could be helpful to show how I did it locally.

## Where to run the docker command

Related to the previous section; automating it, I took care to allow the container to be executed from the project root. If you test and it works, we can remove the paragraph about not calling `docker` from the project root.

## Browser and extensions

Almost forgot this one. I am able to use the browser platform, but only on Chrome. For some reason the log in page didn't work on Firefox.

Also, I had to disable the uBlock origin extension. So might be worth either testing to confirm, or just adding a note in the installation notes to look  at the browser console for possible issues, and trying different browsers and enable/disabling extensions.

**Comment by pmkruyen** [comment]
Aha, thanks Bruno. I now see/read this issue! OK! I'll integrate these remarks/suggestions in the wiki page (see my latest comment in #20). 
Peter

**Comment by kinow** [comment]
Feel free to close this issue now or later after you have updated the Wiki @pmkruyen :+1:
