### ISSUE TITLE
Location of Docker files

### ISSUE THREAD

**Issue by pmkruyen** [pmkruyen/dearscholar#31]
Hi @kinow,

How're you doing? Several researchers want to use (or are using) DearScholar. Based on their feedback, I'm going to update some features.

As a first step, I dowloaded and installed the Docker image again. I try to change the dearscholar.php folder in the phpMyAdmin directory as we suggested in the Wiki. However, I cannot find the mysql folder on my Mac. 

Do you have any ideas where the folder is located? Or do I need to adjust the Docker image instead?

Hope you have some time to help me out,
Best,
Peter

**Comment by kinow** [comment]
Hi Peter,

All good over here, hope you are doing well too.

Glad to hear you got users!

>As a first step, I dowloaded and installed the Docker image again. I try to change the dearscholar.php folder in the phpMyAdmin directory as we suggested in the Wiki. However, I cannot find the mysql folder on my Mac.

Are you talking about this Wiki paragraph?

>IV) Put dearscholar.php in the /app folder
>
>To let DearScholar communicate with the MySQL tables, move the file dearscholar.php to the /app folder created by mattrayner/lamp

Did you move the `dearscholar.php` file to the `/app` folder? I think you have an `App` folder, but we are talking about the other `App` folder (if I recall correctly)

>⚠️ Be aware that /app folder created by mattrayner/lamp is not the /app folder of DearScholar.

If you want to access the MySQL directory and files within the container, you can either access it after you started the container or mount a volume and use it when starting the container.

The former will keep the data until you stop/remove the container, whilst the latter will keep the volume even if the container is deleted - https://github.com/mattrayner/docker-lamp#persisting-your-mysql

Bruno

**Comment by pmkruyen** [comment]
Hi Bruno,

Great to hear. Yes, I'm doing well too, looking forward to improving DearScholar :)

Thanks for your reply.  Yes, I'm talking about this part of the Wiki section,

The thing is, I cannot find the` /var/lib/mysql` folder on my system. There is a ` /var/lib/` folder, but this folder doesn't contain anything. (neither an app folder is created).

I will continue searching for the folders...

Peter

**Comment by kinow** [comment]
Hi Peter

The folder exists inside the container. When you create a container, everything is contained within that system. You can expose ports and volumes.

If you map a volume, that's similar to when you create a VirtualBox or VMWare VM, and you share a folder with the host. You could, for instance, create a local folder like `/test/mysql` in your computer and map to `/var/lib/mysql` inside the container.
